<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->truncate();

        $data = [
            'category_name' => 'AC_REFRIGERATION_REPAIR',
            'category_name' => 'ACADEMIC_SOFTWARE',
            'category_name' => 'ACCESSORIES',
            'category_name' => 'ACCOUNTING',
            'category_name' => 'ADULT',
            'category_name' => 'ADVERTISING',
            'category_name' => 'AFFILIATED_AUTO_RENTAL',
            'category_name' => 'AGENCIES',
            'category_name' => 'AGGREGATORS',
            'category_name' => 'AGRICULTURAL_COOPERATIVE_FOR_MAIL_ORDER',
            'category_name' => 'AIR_CARRIERS_AIRLINES',
            'category_name' => 'AIRLINES',
            'category_name' => 'AIRPORTS_FLYING_FIELDS',
            'category_name' => 'ALCOHOLIC_BEVERAGES',
            'category_name' => 'AMUSEMENT_PARKS_CARNIVALS',
            'category_name' => 'ANIMATION',
            'category_name' => 'ANTIQUES',
            'category_name' => 'APPLIANCES',
            'category_name' => 'AQUARIAMS_SEAQUARIUMS_DOLPHINARIUMS',
            'category_name' => 'ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES',
            'category_name' => 'ART_AND_CRAFT_SUPPLIES',
            'category_name' => 'ART_DEALERS_AND_GALLERIES',
            'category_name' => 'ARTIFACTS_GRAVE_RELATED_AND_NATIVE_AMERICAN_CRAFTS',
            'category_name' => 'ARTS_AND_CRAFTS',
            'category_name' => 'ARTS_CRAFTS_AND_COLLECTIBLES',
            'category_name' => 'AUDIO_BOOKS',
            'category_name' => 'AUTO_ASSOCIATIONS_CLUBS',
            'category_name' => 'AUTO_DEALER_USED_ONLY',
            'category_name' => 'AUTO_RENTALS',
            'category_name' => 'AUTO_SERVICE',
            'category_name' => 'AUTOMATED_FUEL_DISPENSERS',
            'category_name' => 'AUTOMOBILE_ASSOCIATIONS',
            'category_name' => 'BABIES_CLOTHING_AND_SUPPLIES',
            'category_name' => 'BATH_AND_BODY',
            'category_name' => 'BATTERIES',
            'category_name' => 'BEAUTY',
            'category_name' => 'BEAUTY_AND_FRAGRANCES',
            'category_name' => 'BED_AND_BATH',
            'category_name' => 'BICYCLE_SHOPS_SALES_AND_SERVICE',
            'category_name' => 'BICYCLES_AND_ACCESSORIES',
            'category_name' => 'BILLIARD_POOL_ESTABLISHMENTS',
            'category_name' => 'BOAT_DEALERS',
            'category_name' => 'BOAT_RENTALS_AND_LEASING',
            'category_name' => 'BOATING_SAILING_AND_ACCESSORIES',
            'category_name' => 'BOOKS',
            'category_name' => 'BOOKS_AND_MAGAZINES',
            'category_name' => 'BOOKS_PERIODICALS_AND_NEWSPAPERS',
            'category_name' => 'CABLE_SATELLITE_AND_OTHER_PAY_TELEVISION_AND_RADIO_SERVICES',
            'category_name' => 'CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO',
            'category_name' => 'CAMERA_AND_PHOTOGRAPHIC_SUPPLIES',
            'category_name' => 'CAMERAS',
            'category_name' => 'CAMERAS_AND_PHOTOGRAPHY',
            'category_name' => 'CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS',
            'category_name' => 'CAMPING_AND_OUTDOORS',
            'category_name' => 'CAMPING_AND_SURVIVAL',
            'category_name' => 'CAR_AND_TRUCK_DEALERS',
            'category_name' => 'CAR_RENTAL_AGENCY',
            'category_name' => 'CATALOG_MERCHANT',
            'category_name' => 'CATALOG_RETAIL_MERCHANT',
            'category_name' => 'CATERING_SERVICES',
            'category_name' => 'CHARITY',
            'category_name' => 'CHECK_CASHIER',
            'category_name' => 'CHILD_CARE_SERVICES',
            'category_name' => 'CHILDREN_BOOKS',
            'category_name' => 'CHIROPODISTS_PODIATRISTS',
            'category_name' => 'CHIROPRACTORS',
            'category_name' => 'CIGAR_STORES_AND_STANDS',
            'category_name' => 'CIVIC_SOCIAL_FRATERNAL_ASSOCIATIONS',
            'category_name' => 'CIVIL_SOCIAL_FRAT_ASSOCIATIONS',
            'category_name' => 'CLOTHING',
            'category_name' => 'CLOTHING_ACCESSORIES_AND_SHOES',
            'category_name' => 'CLOTHING_RENTAL',
            'category_name' => 'COFFEE_AND_TEA',
            'category_name' => 'COIN_OPERATED_BANKS_AND_CASINOS',
            'category_name' => 'COLLECTIBLES',
            'category_name' => 'COLLECTION_AGENCY',
            'category_name' => 'COLLEGES_AND_UNIVERSITIES',
            'category_name' => 'COMMERCIAL_EQUIPMENT',
            'category_name' => 'COMMERCIAL_FOOTWEAR',
            'category_name' => 'COMMERCIAL_PHOTOGRAPHY',
            'category_name' => 'COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS',
            'category_name' => 'COMMERCIAL_SPORTS_PROFESSIONA',
            'category_name' => 'COMMODITIES_AND_FUTURES_EXCHANGE',
            'category_name' => 'COMPUTER_AND_DATA_PROCESSING_SERVICES',
            'category_name' => 'COMPUTER_HARDWARE_AND_SOFTWARE',
            'category_name' => 'COMPUTER_MAINTENANCE_REPAIR_AND_SERVICES_NOT_ELSEWHERE_CLAS',
            'category_name' => 'CONSTRUCTION',
            'category_name' => 'DAIRY_PRODUCTS_STORES',
            'category_name' => 'DANCE_HALLS_STUDIOS_AND_SCHOOLS',
            'category_name' => 'DECORATIVE',
            'category_name' => 'DENTAL',
            'category_name' => 'DENTISTS_AND_ORTHODONTISTS',
            'category_name' => 'DEPARTMENT_STORES',
            'category_name' => 'DESKTOP_PCS',
            'category_name' => 'DEVICES',
            'category_name' => 'DIECAST_TOYS_VEHICLES',
            'category_name' => 'DIGITAL_GAMES',
            'category_name' => 'DIGITAL_MEDIA_BOOKS_MOVIES_MUSIC',
            'category_name' => 'DIRECT_MARKETING',
            'category_name' => 'DIRECT_MARKETING_CATALOG_MERCHANT',
            'category_name' => 'DIRECT_MARKETING_INBOUND_TELE',
            'category_name' => 'DIRECT_MARKETING_OUTBOUND_TELE',
            'category_name' => 'DIRECT_MARKETING_SUBSCRIPTION',
            'category_name' => 'DISCOUNT_STORES',
            'category_name' => 'DOOR_TO_DOOR_SALES',
            'category_name' => 'DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY',
            'category_name' => 'DRINKING_PLACES',
            'category_name' => 'DRUGSTORE',
            'category_name' => 'DURABLE_GOODS',
            'category_name' => 'ECOMMERCE_DEVELOPMENT',
            'category_name' => 'ECOMMERCE_SERVICES',
            'category_name' => 'EDUCATIONAL_AND_TEXTBOOKS',
            'category_name' => 'ELECTRIC_RAZOR_STORES',
        ];
    }
}
